routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('oauth/{driver}', 'App\Http\Controllers\Auth\LoginController@redirectToProvider')->name('social.oauth');
Route::get('oauth/{driver}/callback', 'App\Http\Controllers\Auth\LoginController@handleProviderCallback')->name('social.callback');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::resource('ads', 'App\Http\Controllers\admin\AdsController');
    Route::resource('users', 'App\Http\Controllers\admin\UsersController');

});


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Route::resource('users', 'admin\UserController');
//Route::resource('ads', 'App\Http\Controllers\admin\AdsController');

app/Models/Ad.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ad extends Model
{
    use HasFactory;
    protected $fillable = [
        'title',
        'description',
        'contact_phone',
        'user_id'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/admin/AdsController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Ad;
use App\Http\Requests\StoreAdRequest;
use App\Http\Requests\UpdateAdRequest;
use Illuminate\Support\Facades\Auth;
use Session;

class AdsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $ads = Ad::all();
        $page_title='Ads';
        $page_description='List of All Ads';
        return view('admin.ads.list',compact('page_title', 'page_description','ads'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $page_title='Ads';
        $page_description='Create New Ad';
        return view('admin.ads.create',compact('page_title', 'page_description'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreAdRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAdRequest $request)
    {
        //
        $inputs = $request->except(['_token']);
        $inputs['user_id']=\Auth::user()->id;
        $ad = Ad::create($inputs);
        Session::flash('message', 'Ad created Successfully');
        Session::flash('alert-class', ' alert-success');

        return redirect('ads');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Ad  $ad
     * @return \Illuminate\Http\Response
     */
    public function show(Ad $ad)
    {
        //
        $page_title='Ads';
        $page_description='Show Ad Details';
        return view('admin.ads.show',compact('ad','page_title','page_description'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Ad  $ad
     * @return \Illuminate\Http\Response
     */
    public function edit(Ad $ad)
    {
        //
        $page_title='Ads';
        $page_description='Edit Ad';
        return view('admin.ads.edit',compact('ad','page_title','page_description'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateAdRequest  $request
     * @param  \App\Models\Ad  $ad
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAdRequest $request, Ad $ad)
    {
        //
        $ad->update($request->all());
        Session::flash('message', 'Ad Modified Successfully');
        Session::flash('alert-class', ' alert-success');
        return redirect()->route('ads.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Ad  $ad
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ad $ad)
    {
        //
        $ad->delete();
        Session::flash('message', 'Ad deleted Successfully');
        Session::flash('alert-class', ' alert-success');
        return redirect()->route('ads.index');
    }
}

app/Http/Controllers/api/AdsController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Ad;
use App\Http\Resources\Ad as AdResource;
use Illuminate\Support\Facades\Auth;
use App\Jobs\ProceessFiles;
use Validator;
use Config;
use DB;

class AdsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $ads = Ad::select('id','title',DB::raw("SUBSTR(description, 1, 512)  AS description"))->orderBy('id', 'desc')->paginate(10);

        return response(['ads' => AdResource::collection($ads), 'message' => 'Retrieved successfully'], 200);

        // return $this->sendResponse(AdResource::collection($ads), 'Ads retrieved successfully.');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $input = $request->all();
   
        $validator = Validator::make($input, [
            'title' => 'required',
            'description' => 'required',
            'contact_phone' => 'required',
        ]);
   
        if($validator->fails()){
            return $this->sendError('Validation Error.', $validator->errors());       
        }
        if($validator->fails()){
            return response(['error' => $validator->errors(), 'Validation Error']);
        }

        $user = Auth::user(); 
        $input['user_id']=$user->id;
        $ad = Ad::create($input);

        return response([ 'ad' => new AdResource($ad), 'message' => 'Created successfully'], 201);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $objAd = Ad::find($id);
        if (is_null($objAd)) {
            return $this->sendError('Ad not found!');
        }
        $objAd['user_name']=$objAd->user->name;
        unset($objAd['user']);

        return response([ 'ad' => $objAd, 'message' => 'Retrieved successfully'], 200);
    }

    public function uploadImage(Request $request, $id)
    {
        $input = $request->all();
        $validator = Validator::make($input, [
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg',
        ]);
   
        if($validator->fails()){
            return $this->sendError('Validation Error.', $validator->errors());       
        }
        $ad=Ad::find($id);
        if(!$ad)
        {
             return $this->sendError('Ad Or Post Not Found');
        }
        $image=$request->image;
        $fileName = $image->store(Config::get('constants.ADS_IMAGE_PATH'));
        $ad->image=$fileName;
        $ad->save();

        //dispatch(new ProceessFiles ($request->image));
        return response([ 'ad' => new AdResource($ad), 'message' => 'Ad Image  Uploaded successfully'], 200);


    }

    public function getuserAds($userid)
    {
        $arrAds = Ad::where('user_id',$userid)->get();
        return response([ 'ads' => $arrAds, 'message' => 'user Ads Retrieved successfully'], 200);
    }

}

resources/views/admin/ads/create.blade.php
@extends('layouts.app')
@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">{{ $page_title }}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">{{ $page_title }}</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">{{ $page_description }} </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form id="quickForm" method="POST" action="{{ url('ads') }}">
                 @csrf
                <div class="card-body">

                  <div class="form-group">
                    <label for="exampleInputAdTitle1">{{ __('Ad Title') }}</label>
                    <input type="text" name="title" class="form-control" id="exampleInputAdTitle1" placeholder="{{ __('Ad Title') }}">
                  </div>

                  <div class="form-group">
                    <label for="exampleInputAdDescription1">{{ __('Ad Description') }}</label>
                    <textarea name="description" class="form-control" id="exampleInputAdDescription1" placeholder="{{ __('Ad Description') }}"></textarea> 
                  </div>
                  <div class="form-group">
                    <label for="exampleInputContactPhone1">{{ __('Contact Phone') }}</label>
                    <input type="text" name="contact_phone" class="form-control" id="exampleInputContactPhone1" placeholder="{{ __('Contact Phone') }}">
                  </div>

                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->


    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  @endsection 

  @section('scripts')
    <script src="{{ asset('assets/plugins/jquery-validation/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/jquery-validation/additional-methods.min.js') }}"></script>
    <script>
      $(function () {
        $.validator.setDefaults({
          submitHandler: function () {
            $("#quickForm").ajaxForm({url: '{{ url("ads") }}', type: 'post'})

    
          }
        });
        $('#quickForm').validate({
          rules: {
            title: {
              required: true,
            },
            description: {
              required: true,
              minlength: 5
            },
            contact_phone: {
              required: true
            },
          },
          messages: {
            title: {
              required: "Please enter a Ad Title",
            },
            description: {
              required: "Please Enter a description",
              minlength: "Your description must be at least 5 characters long"
            },
            contact_phone: "Please enter a contact phone"
          },
          errorElement: 'span',
          errorPlacement: function (error, element) {
            error.addClass('invalid-feedback');
            element.closest('.form-group').append(error);
          },
          highlight: function (element, errorClass, validClass) {
            $(element).addClass('is-invalid');
          },
          unhighlight: function (element, errorClass, validClass) {
            $(element).removeClass('is-invalid');
          }
        });
      });
      </script>


  @endsection

resources/views/admin/ads/edit.blade.php
@extends('layouts.app')
@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">{{ $page_title }}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">{{ $page_title }}</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">{{ $page_description }} </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form id="quickForm" method="POST" action="{{ route('ads.update',$ad->id) }}">
                 @csrf
                 @method('PUT')
                <div class="card-body">

                  <div class="form-group">
                    <label for="exampleInputAdTitle1">{{ __('Ad Title') }}</label>
                    <input type="text" name="title" class="form-control" id="exampleInputAdTitle1" placeholder="{{ __('Ad Title') }}" value="{{ $ad->title }}">
                  </div>

                  <div class="form-group">
                    <label for="exampleInputAdDescription1">{{ __('Ad Description') }}</label>
                    <textarea name="description" class="form-control" id="exampleInputAdDescription1" placeholder="{{ __('Ad Description') }}">{{ $ad->description }}</textarea> 
                  </div>
                  <div class="form-group">
                    <label for="exampleInputContactPhone1">{{ __('Contact Phone') }}</label>
                    <input type="text" name="contact_phone" class="form-control" id="exampleInputContactPhone1" placeholder="{{ __('Contact Phone') }}" value="{{ $ad->contact_phone }}">
                  </div>

                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->


    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  @endsection 

  @section('scripts')
    <script src="{{ asset('assets/plugins/jquery-validation/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/jquery-validation/additional-methods.min.js') }}"></script>
    <script>
      $(function () {
        $.validator.setDefaults({
          submitHandler: function () {
            $("#quickForm").ajaxForm({url: '{{ route('ads.update',$ad->id) }}', type: 'PUT'})

    
          }
        });
        $('#quickForm').validate({
          rules: {
            title: {
              required: true,
            },
            description: {
              required: true,
              minlength: 5
            },
            contact_phone: {
              required: true
            },
          },
          messages: {
            title: {
              required: "Please enter a Ad Title",
            },
            description: {
              required: "Please Enter a description",
              minlength: "Your description must be at least 5 characters long"
            },
            contact_phone: "Please enter a contact phone"
          },
          errorElement: 'span',
          errorPlacement: function (error, element) {
            error.addClass('invalid-feedback');
            element.closest('.form-group').append(error);
          },
          highlight: function (element, errorClass, validClass) {
            $(element).addClass('is-invalid');
          },
          unhighlight: function (element, errorClass, validClass) {
            $(element).removeClass('is-invalid');
          }
        });
      });
      </script>


  @endsection

resources/views/admin/ads/list.blade.php
@extends('layouts.app')
@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">{{ $page_title }}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">{{ $page_title }}</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
     <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">

            <div class="card">
              <div class="card-header">
                <h3 class="card-title">{{ $page_description }}</h3>
                &nbsp;
                <a class="btn btn-primary btn-sm" href="{{url('')}}/ads/create">
                    <i class="fas fa-plus"></i> Add New Ad
                </a>

              </div>
              @include('layouts.messages')
              
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>Ad ID</th>
                    <th>Ad Title</th>
                    <th>Ad Description</th>
                    <th> Contact Phone</th>
                    <th>Created User</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                  @foreach($ads as $ad)
                    <tr>
                      <td>{{ $ad->id }}</td>
                      <td>{{ $ad->title }}</td>
                      <td>{{ $ad->description }}</td>
                      <td>{{ $ad->contact_phone }}</td>
                      <td>{{ $ad->user->name }}</td>
                      <td>
                          <a class="btn btn-primary btn-sm" href="{{ route('ads.show',$ad->id) }}">
                              <i class="fas fa-folder">
                              </i>
                              View
                          </a>

                          <a class="btn btn-info btn-sm" href="{{ route('ads.edit',$ad->id) }}">
                              <i class="fas fa-pencil-alt">
                              </i>
                              Edit
                          </a>

                          <form action="{{ route('ads.destroy',$ad->id) }}" method="POST">
   
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger"> <i class="fas fa-trash">
                              </i> Delete</button>
                          </form>

                      </td>
                    </tr>
                  @endforeach
                  
                  </tbody>
                  <tfoot>
                  <tr>
                    <th>Ad ID</th>
                    <th>Ad Title</th>
                    <th>Ad Description</th>
                    <th> Contact Phone</th>
                    <th>Created User</th>
                    <th>Action</th>
                  </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  @endsection 

  @section('scripts')
    <script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/jszip/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/pdfmake/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/pdfmake/vfs_fonts.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
    <script>
      $(function () {
        $("#example1").DataTable({
          "responsive": true, "lengthChange": false, "autoWidth": false,
          "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false,
          "responsive": true,
        });
      });
    </script>


  @endsection

resources/views/admin/ads/show.blade.php
@extends('layouts.app')
@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">{{ $page_title }}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">{{ $page_title }}</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
     <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">{{ $page_description }}</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-12 col-lg-12 order-2 order-md-1">
              <div class="row">

                <div class="col-12 col-sm-3">
                  <div class="info-box bg-light">
                    <div class="info-box-content">
                      <span class="info-box-text text-center text-muted">{{ __('Ad Title') }}</span>
                      <span class="info-box-number text-center text-muted mb-0">{{ $ad->title }}</span>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-sm-3">
                  <div class="info-box bg-light">
                    <div class="info-box-content">
                      <span class="info-box-text text-center text-muted">{{ __('Ad Description') }}</span>
                      <span class="info-box-number text-center text-muted mb-0">{{ $ad->description }}</span>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-sm-3">
                  <div class="info-box bg-light">
                    <div class="info-box-content">
                      <span class="info-box-text text-center text-muted">{{ __('Contact Phone') }}</span>
                      <span class="info-box-number text-center text-muted mb-0">{{ $ad->contact_phone }}</span>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-sm-3">
                  <div class="info-box bg-light">
                    <div class="info-box-content">
                      <span class="info-box-text text-center text-muted">{{ __('Created User') }}</span>
                      <span class="info-box-number text-center text-muted mb-0">{{ $ad->user->name }}</span>
                    </div>
                  </div>
                </div>


               
              </div>
               
            </div>
             
          </div>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  @endsection 

  